name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]
env:
  VITE_API_TEST: ${{secrets.VITE_API_TEST}}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install, build 🔧
        run: |
          npm install
          npm run build
          cp ./dist/index.html ./dist/404.html
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
          VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
          VITE_AUTH_DOMAIN: ${{ secrets.VITE_AUTH_DOMAIN }}
          VITE_DATABASE_URI: ${{ secrets.VITE_DATABASE_URI }}
          VITE_MESSAGING_SENDER_ID: ${{ secrets.VITE_MESSAGING_SENDER_ID }}
          VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
          VITE_STORAGE_BUCKET: ${{ secrets.VITE_STORAGE_BUCKET}}
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: dist